version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: npm ci
      - run: npm run style
      - run: npm run lint
      - run: npm run build:prod
      - run: npm test -- --watch=false --code-coverage
      - run: npm run e2e

      - store_test_results:
          path: ./test_results
      - store_artifacts:
          path: ./coverage

      - coveralls/upload
          path_to_lcov: ./coverage/lemon-mart/lcov.info
      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/lemon-mart
      - store_artifacts:
          path: dist.tar.gz

      - run:
          name: Execute Pipeline (Build Source -> Test -> Build Web Server)
          command: |
            docker build -f integration.Dockerfile . -t lemon-mart:$CIRCLE_BRANCH
            mkdir -p docker-cache
            docker save lemon-mart:$CIRCLE_BRANCH | gzip > dockercache/built-image.tar.gz
      - save_cache:
          key: built-image-{{ .BuildNum }}
          paths:
            - docker-cache
      - store_artifacts:
          path: docker-cache/built-image.tar.gz
          destination: built-image.tar.gz
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
